#!/usr/bin/env python3
"""Build the VMware API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'NSX-T Data Center': 'NSX-T DC',
    'NSX-T Global Mgr': 'NSX-T Global',
    'NSX Intelligence': 'NSX Intel.',
    'NSX Autonomous Edge': 'NSX Edge',
    'NSX VMC Policy': 'NSX VMC',
    'vRealize Auto': 'vRA',
    'vRealize Ops': 'vROps',
    'Aria for Logs': 'Aria Logs',
    'Aria for Networks': 'Aria Networks',
    'Aria Lifecycle': 'Aria Lifecycle',
    'Site Recovery Mgr': 'SRM',
    'Live Cyber Recovery': 'Live Cyber',
    'Live Site Recovery': 'Live Site',
    'Cloud DR': 'Cloud DR',
    'Workspace ONE': 'Workspace ONE',
    'Identity Mgr': 'Identity Mgr',
    'Horizon Server': 'Horizon',
    'App Volumes': 'App Volumes',
    'Tanzu Kubernetes': 'Tanzu K8s',
    'vSphere K8s Svc': 'vSphere K8s',
    'vSAN Mgmt': 'vSAN',
    'Avi Load Balancer': 'Avi LB',
    'VMware Cloud AWS': 'VMC on AWS',
    'Cloud Foundation': 'VCF',
    'vCloud Director': 'vCD',
    'VCF Operations': 'VCF Ops',
    'VCF Ops Networks': 'VCF Ops Net',
    'VCF Ops Orchestrator': 'VCF Ops Orch',
    'Operations for Apps': 'Ops for Apps',
}

LINES = [
    {
        "name": 'vSphere & Cloud Foundation',
        "color": '#3CC2A7',
        "stations": [
        ('vSphere', (270, 195)),
        ('vSphere Web Svcs', (430, 175)),
        ('vCloud Director', (610, 165)),
        ('VMware Cloud AWS', (810, 175)),
        ('Cloud Foundation', (1000, 200)),
        ],
    },
    {
        "name": 'Networking (NSX)',
        "color": '#0072CE',
        "stations": [
        ('NSX-T Data Center', (270, 310)),
        ('NSX-T Global Mgr', (430, 285)),
        ('NSX Intelligence', (610, 285)),
        ('NSX Autonomous Edge', (810, 285)),
        ('NSX VMC Policy', (1000, 310)),
        ],
    },
    {
        "name": 'Aria Operations',
        "color": '#7B3FE4',
        "stations": [
        ('vRealize Auto', (270, 425)),
        ('vRealize Ops', (430, 405)),
        ('Aria for Logs', (610, 405)),
        ('Aria for Networks', (810, 405)),
        ('Aria Lifecycle', (1000, 425)),
        ],
    },
    {
        "name": 'Cloud DR & SRM',
        "color": '#E68B1F',
        "stations": [
        ('Site Recovery Mgr', (270, 540)),
        ('Live Cyber Recovery', (450, 515)),
        ('Live Site Recovery', (640, 515)),
        ('Cloud DR', (820, 540)),
        ],
    },
    {
        "name": 'Workspace ONE & Identity',
        "color": '#C5318B',
        "stations": [
        ('Workspace ONE', (270, 660)),
        ('Identity Mgr', (430, 635)),
        ('Horizon Server', (610, 635)),
        ('View', (790, 635)),
        ('App Volumes', (950, 660)),
        ],
    },
    {
        "name": 'Storage & Compute',
        "color": '#0E9D6E',
        "stations": [
        ('Tanzu Kubernetes', (270, 770)),
        ('vSphere K8s Svc', (450, 745)),
        ('vSAN Mgmt', (640, 745)),
        ('Avi Load Balancer', (820, 770)),
        ],
    },
    {
        "name": 'VCF Operations',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('VCF Operations', (790, 815)),
        ('VCF Ops Networks', (905, 815)),
        ('VCF Ops Orchestrator', (790, 815)),
        ('Operations for Apps', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'vSphere': 'https://apis.apis.io/apis/vmware/vsphere-api/',
    'vSphere Web Svcs': 'https://apis.apis.io/apis/vmware/vsphere-web-services-api/',
    'vCloud Director': 'https://apis.apis.io/apis/vmware/vcloud-director-api/',
    'VMware Cloud AWS': 'https://apis.apis.io/apis/vmware/vmware-cloud-on-aws-api/',
    'Cloud Foundation': 'https://apis.apis.io/apis/vmware/vmware-cloud-foundation-api/',
    'NSX-T Data Center': 'https://apis.apis.io/apis/vmware/nsx-t-data-center-api/',
    'NSX-T Global Mgr': 'https://apis.apis.io/apis/vmware/nsx-t-global-manager-api/',
    'NSX Intelligence': 'https://apis.apis.io/apis/vmware/nsx-intelligence-api/',
    'NSX Autonomous Edge': 'https://apis.apis.io/apis/vmware/nsx-autonomous-edge-api/',
    'NSX VMC Policy': 'https://apis.apis.io/apis/vmware/nsx-vmc-policy-api/',
    'vRealize Auto': 'https://apis.apis.io/apis/vmware/vrealize-automation-api/',
    'vRealize Ops': 'https://apis.apis.io/apis/vmware/vrealize-operations-api/',
    'Aria for Logs': 'https://apis.apis.io/apis/vmware/vmware-aria-operations-for-logs-api/',
    'Aria for Networks': 'https://apis.apis.io/apis/vmware/vmware-aria-operations-for-networks-api/',
    'Aria Lifecycle': 'https://apis.apis.io/apis/vmware/vmware-aria-suite-lifecycle-api/',
    'Site Recovery Mgr': 'https://apis.apis.io/apis/vmware/vmware-site-recovery-manager-api/',
    'Live Cyber Recovery': 'https://apis.apis.io/apis/vmware/vmware-live-cyber-recovery-api/',
    'Live Site Recovery': 'https://apis.apis.io/apis/vmware/vmware-live-site-recovery-api/',
    'Cloud DR': 'https://apis.apis.io/apis/vmware/vmware-cloud-disaster-recovery-api/',
    'Workspace ONE': 'https://apis.apis.io/apis/vmware/workspace-one-api/',
    'Identity Mgr': 'https://apis.apis.io/apis/vmware/vmware-identity-manager-api/',
    'Horizon Server': 'https://apis.apis.io/apis/vmware/vmware-horizon-server-api/',
    'View': 'https://apis.apis.io/apis/vmware/vmware-view-api/',
    'App Volumes': 'https://apis.apis.io/apis/vmware/app-volumes-api/',
    'Tanzu Kubernetes': 'https://apis.apis.io/apis/vmware/tanzu-kubernetes-grid-api/',
    'vSphere K8s Svc': 'https://apis.apis.io/apis/vmware/vmware-vsphere-kubernetes-service-api/',
    'vSAN Mgmt': 'https://apis.apis.io/apis/vmware/vsan-management-api/',
    'Avi Load Balancer': 'https://apis.apis.io/apis/vmware/vmware-avi-load-balancer-api/',
    'VCF Operations': 'https://apis.apis.io/apis/vmware/vcf-operations-api/',
    'VCF Ops Networks': 'https://apis.apis.io/apis/vmware/vcf-operations-for-networks-api/',
    'VCF Ops Orchestrator': 'https://apis.apis.io/apis/vmware/vcf-operations-orchestrator-api/',
    'Operations for Apps': 'https://apis.apis.io/apis/vmware/operations-for-applications-rest-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The VMware API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: vmware/openapi · github.com/api-evangelist/vmware',
        out_dir=Path(__file__).resolve().parent,
        out_basename='vmware-subway-map',
        provider_id='vmware',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
